# Generated by Django 5.1.1 on 2024-09-25 19:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn13",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
