# Generated by Django 5.1.1 on 2024-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
