# Generated by Django 5.1.1 on 2024-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_isbn13"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="book",
            name="original_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
