# Generated by Django 5.1.1 on 2024-09-27 21:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_language_code_alter_book_original_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn13",
            field=models.CharField(max_length=15),
        ),
    ]
