# Generated by Django 5.1.1 on 2024-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_book_id_alter_book_isbn13"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn13",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
