# Generated by Django 5.1.1 on 2024-09-27 21:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_authors_alter_book_isbn_alter_book_isbn13"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.TextField(blank=True),
        ),
    ]
