# Generated by Django 5.1.1 on 2024-09-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
