# Generated by Django 5.1.1 on 2024-09-30 14:51

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_bookreserve"),
    ]

    operations = [TrigramExtension()]
