# Generated by Django 5.1.1 on 2024-09-30 14:51

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_enable_gin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=GinIndex(
                fields=["title"], name="gin_title_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=GinIndex(
                fields=["authors"], name="gin_authors_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=GinIndex(
                fields=["isbn13"], name="gin_isbn13_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["language_code"], name="language_code_idx"),
        ),
    ]
